name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SUPABASE_CONNECTION_STRING: ${{ secrets.SUPABASE_CONNECTION_STRING }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ScrumAPI/lobby-service.Tests

      - name: Build
        run: dotnet build --no-restore
        working-directory: ScrumAPI/lobby-service.Tests

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
        working-directory: ScrumAPI/lobby-service.Tests
