name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SUPABASE_CONNECTION_STRING: ${{ secrets.SUPABASE_CONNECTION_STRING }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Check SUPABASE_CONNECTION_STRING environment variable
        run: |
          echo "SUPABASE_CONNECTION_STRING=${SUPABASE_CONNECTION_STRING}"
          if [ -z "${SUPABASE_CONNECTION_STRING}" ]; then
            echo "Error: SUPABASE_CONNECTION_STRING is not set."
            exit 1
          else
            echo "Connection string detected."
          fi

      - name: Test connection to Supabase
        run: |
          nc -zv db.xyz.supabase.co 5432 || exit 1
            
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ScrumAPI/lobby-service.Tests

      - name: Build
        run: dotnet build --no-restore
        working-directory: ScrumAPI/lobby-service.Tests

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
        working-directory: ScrumAPI/lobby-service.Tests